[StyleTitle]
FontFace=#FontPrimary#
FontSize=12
FontColor=#ColorSecondary#
AntiAlias=1

[StyleSubTitle]
FontFace=#FontPrimary#
FontSize=10
FontColor=#ColorSecondaryLight#
AntiAlias=1

[StyleBarLeft]
FontFace=#FontPrimary#
FontSize=8
FontColor=#ColorPrimary#
AntiAlias=1

[StyleBarRight]
FontFace=#FontPrimary#
FontSize=8
FontColor=#ColorSecondary#
AntiAlias=1
StringAlign=Right

[StyleBar]
BarColor=#ColorSecondary#
BarOrientation=Horizontal
SolidColor=#ColorPrimary#